name: Deploy Theme via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: appleboy/sftp-action@v0.1.4
      with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          target: ${{ secrets.FTP_SERVER_DIR }}
          source: ./  # 🔥 Use current directory (theme is the repo root)
          protocol: ftps
          port: 22